name: Deployment
on:
  push:
    branches:
      - master

jobs:
  create_ssh:
    runs-on: ubuntu-latest
    steps:
    - name: test ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          touch abc.de
        
