name: Deployment
on:
  push:
    branches:
      - master

jobs:
  create_ssh:
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      continue-on-error: true
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.TARGET }}
          sudo pkill -f "node main.js"
          git pull
          nohup node main.js &
