name: Deployment
on:
  push:
    branches:
      - master

jobs:
  create_ssh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Send greeting
      run: echo "Hello"
    - name: ree
      env:
        HOST: ${{ secrets.HOST }}
      run: |
        ls -lla
        touch text.txt
        echo $HOST > text.txt
        ls -lla
        cat text.txt
