name: Deployment
on:
  push:
    branches:
      - master

jobs:
  create_ssh:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Send greeting
      run: echo "Hello"
    - name: ree
      run: |
        ls -lla
        cat '${{ secrets.host }}' > text.txt
        ls -lla
        cat text.txt
